sudo: required
language: scala
scala:
  - 2.11.11
  - 2.12.6
jdk: oraclejdk8
services:
  - docker
  - postgresql
  - mysql
addons:
  postgresql: "9.6"
script:
  - ./build/build.sh
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.m2
    - $HOME/.sbt
